### ISSUE TITLE
Add Preemptice Scheduling

### ISSUE THREAD

**Issue by knuffel-v2** [knuffel-v2/OTOS#1]
# Expected Behavior
The task execution should be interrupted by the kernel and the *SysTick* timer should be used to schedule the next task to be executed.

**Comment by knuffel-v2** [comment]
# Todos for Preemptive Scheduling
- [ ] Add *SysTick* interrupt
- [ ] Add tick counters for every thread
- [ ] Take the priority of threads into account.

**Comment by knuffel-v2** [comment]
# Update

The current work enables a priority and timing based scheduling. But there is no preemption out of the box yet.
The rationale behind this is to not interrupt critical threads and hardware dependent threads in the middle of
their execution. A real-time application should anyhow put some thought into the correct schedule and not rely
on the OS to do that.

# Upcoming
The current thread scheduling can probably just be executed in an interrupt and then preemption should be possible,
but this has to be tested first! Also the current scheduling is computed every `1 ms` which may be to fast for the
preemptive version.
